export interface ImbuementItem {
  name: string;
  quantity: number;
  image?: string;
}

export interface Imbuement {
  id: string;
  name: string;
  slot: string;
  tier: string;
  effect: string;
  icon: string;
  items: ImbuementItem[];
  cost: number;
  time: string;
}

const WIKI = "https://www.tibiawiki.com.br";

const WIKI_ITEM = (name: string) => `${WIKI}/wiki/Especial:Redirecionar?file=${encodeURIComponent(name)}.gif`;
const WIKI_IMBU = (name: string) => `${WIKI}/wiki/Especial:Redirecionar?file=${encodeURIComponent(name)}.png`;

export const IMBUEMENTS: Imbuement[] = [
  // ====== MANA LEECH ======
  {
    id: "basic-void",
    name: "Void (Basic)",
    slot: "Helmet",
    tier: "Basic",
    effect: "Converte 3% do dano causado em Mana",
    icon: WIKI_IMBU("Imbuement_Mana_Leech1"),
    items: [{ name: "Rope Belt", quantity: 25 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-void",
    name: "Void (Intricate)",
    slot: "Helmet",
    tier: "Intricate",
    effect: "Converte 5% do dano causado em Mana",
    icon: WIKI_IMBU("Imbuement_Mana_Leech2"),
    items: [
      { name: "Rope Belt", quantity: 25 },
      { name: "Silencer Claws", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-void",
    name: "Void (Powerful)",
    slot: "Helmet",
    tier: "Powerful",
    effect: "Converte 8% do dano causado em Mana",
    icon: WIKI_IMBU("Imbuement_Mana_Leech3"),
    items: [
      { name: "Rope Belt", quantity: 25 },
      { name: "Silencer Claws", quantity: 20 },
      { name: "Some Grimeleech Wings", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== LIFE LEECH ======
  {
    id: "basic-vampirism",
    name: "Vampirism (Basic)",
    slot: "Helmet",
    tier: "Basic",
    effect: "Converte 5% do dano causado em HP",
    icon: WIKI_IMBU("Imbuement_Life_Leech1"),
    items: [{ name: "Vampire Teeth", quantity: 25 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-vampirism",
    name: "Vampirism (Intricate)",
    slot: "Helmet",
    tier: "Intricate",
    effect: "Converte 10% do dano causado em HP",
    icon: WIKI_IMBU("Imbuement_Life_Leech2"),
    items: [
      { name: "Vampire Teeth", quantity: 25 },
      { name: "Bloody Pincers", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-vampirism",
    name: "Vampirism (Powerful)",
    slot: "Helmet",
    tier: "Powerful",
    effect: "Converte 25% do dano causado em HP",
    icon: WIKI_IMBU("Imbuement_Life_Leech3"),
    items: [
      { name: "Vampire Teeth", quantity: 25 },
      { name: "Bloody Pincers", quantity: 20 },
      { name: "Piece of Dead Brain", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== CRITICAL ======
  {
    id: "basic-strike",
    name: "Strike (Basic)",
    slot: "Helmet",
    tier: "Basic",
    effect: "Dano crítico: 15% extra, 10% de chance",
    icon: WIKI_IMBU("Imbuement_Critical-Strike1"),
    items: [{ name: "Protective Charm", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-strike",
    name: "Strike (Intricate)",
    slot: "Helmet",
    tier: "Intricate",
    effect: "Dano crítico: 25% extra, 10% de chance",
    icon: WIKI_IMBU("Imbuement_Critical-Strike2"),
    items: [
      { name: "Protective Charm", quantity: 25 },
      { name: "Sabreteeth", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-strike",
    name: "Strike (Powerful)",
    slot: "Helmet",
    tier: "Powerful",
    effect: "Dano crítico: 50% extra, 10% de chance",
    icon: WIKI_IMBU("Imbuement_Critical-Strike3"),
    items: [
      { name: "Protective Charm", quantity: 25 },
      { name: "Sabreteeth", quantity: 20 },
      { name: "Vexclaw Talon", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== DISTANCE SKILL ======
  {
    id: "basic-precision",
    name: "Precision (Basic)",
    slot: "Helmet",
    tier: "Basic",
    effect: "+1 Distance Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Distance1"),
    items: [{ name: "Elven Scouting Glass", quantity: 25 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-precision",
    name: "Precision (Intricate)",
    slot: "Helmet",
    tier: "Intricate",
    effect: "+2 Distance Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Distance2"),
    items: [
      { name: "Elven Scouting Glass", quantity: 25 },
      { name: "Elven Hoof", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-precision",
    name: "Precision (Powerful)",
    slot: "Helmet",
    tier: "Powerful",
    effect: "+4 Distance Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Distance3"),
    items: [
      { name: "Elven Scouting Glass", quantity: 25 },
      { name: "Elven Hoof", quantity: 20 },
      { name: "Metal Spike", quantity: 10 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== MAGIC LEVEL ======
  {
    id: "basic-epiphany",
    name: "Epiphany (Basic)",
    slot: "Helmet",
    tier: "Basic",
    effect: "+1 Magic Level",
    icon: WIKI_IMBU("Imbuement_Skillboost_Magic1"),
    items: [{ name: "Elvish Talisman", quantity: 25 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-epiphany",
    name: "Epiphany (Intricate)",
    slot: "Helmet",
    tier: "Intricate",
    effect: "+2 Magic Level",
    icon: WIKI_IMBU("Imbuement_Skillboost_Magic2"),
    items: [
      { name: "Elvish Talisman", quantity: 25 },
      { name: "Broken Shamanic Staff", quantity: 15 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-epiphany",
    name: "Epiphany (Powerful)",
    slot: "Helmet",
    tier: "Powerful",
    effect: "+4 Magic Level",
    icon: WIKI_IMBU("Imbuement_Skillboost_Magic3"),
    items: [
      { name: "Elvish Talisman", quantity: 25 },
      { name: "Broken Shamanic Staff", quantity: 15 },
      { name: "Strand of Medusa Hair", quantity: 15 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== SWORD FIGHTING ======
  {
    id: "basic-slash",
    name: "Slash (Basic)",
    slot: "Helmet",
    tier: "Basic",
    effect: "+1 Sword Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Sword1"),
    items: [{ name: "Lion's Mane", quantity: 25 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-slash",
    name: "Slash (Intricate)",
    slot: "Helmet",
    tier: "Intricate",
    effect: "+2 Sword Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Sword2"),
    items: [
      { name: "Lion's Mane", quantity: 25 },
      { name: "Mooh'tah Shell", quantity: 25 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-slash",
    name: "Slash (Powerful)",
    slot: "Helmet",
    tier: "Powerful",
    effect: "+4 Sword Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Sword3"),
    items: [
      { name: "Lion's Mane", quantity: 25 },
      { name: "Mooh'tah Shell", quantity: 25 },
      { name: "War Crystal", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== AXE FIGHTING ======
  {
    id: "basic-chop",
    name: "Chop (Basic)",
    slot: "Helmet",
    tier: "Basic",
    effect: "+1 Axe Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Axe1"),
    items: [{ name: "Orc Tooth", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-chop",
    name: "Chop (Intricate)",
    slot: "Helmet",
    tier: "Intricate",
    effect: "+2 Axe Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Axe2"),
    items: [
      { name: "Orc Tooth", quantity: 25 },
      { name: "Battle Stone", quantity: 25 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-chop",
    name: "Chop (Powerful)",
    slot: "Helmet",
    tier: "Powerful",
    effect: "+4 Axe Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Axe3"),
    items: [
      { name: "Orc Tooth", quantity: 25 },
      { name: "Battle Stone", quantity: 25 },
      { name: "Moohtant Horn", quantity: 20 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== CLUB FIGHTING ======
  {
    id: "basic-bash",
    name: "Bash (Basic)",
    slot: "Helmet",
    tier: "Basic",
    effect: "+1 Club Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Club1"),
    items: [{ name: "Cyclops Toe", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-bash",
    name: "Bash (Intricate)",
    slot: "Helmet",
    tier: "Intricate",
    effect: "+2 Club Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Club2"),
    items: [
      { name: "Cyclops Toe", quantity: 25 },
      { name: "Ogre Nose Ring", quantity: 15 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-bash",
    name: "Bash (Powerful)",
    slot: "Helmet",
    tier: "Powerful",
    effect: "+4 Club Fighting",
    icon: WIKI_IMBU("Imbuement_Skillboost_Club3"),
    items: [
      { name: "Cyclops Toe", quantity: 25 },
      { name: "Ogre Nose Ring", quantity: 15 },
      { name: "Warmaster's Wristguards", quantity: 10 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== SHIELDING ======
  {
    id: "basic-blockade",
    name: "Blockade (Basic)",
    slot: "Shield",
    tier: "Basic",
    effect: "+1 Shielding",
    icon: WIKI_IMBU("Imbuement_Skillboost_Shielding1"),
    items: [{ name: "Piece of Scarab Shell", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-blockade",
    name: "Blockade (Intricate)",
    slot: "Shield",
    tier: "Intricate",
    effect: "+2 Shielding",
    icon: WIKI_IMBU("Imbuement_Skillboost_Shielding2"),
    items: [
      { name: "Piece of Scarab Shell", quantity: 25 },
      { name: "Brimstone Shell", quantity: 25 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-blockade",
    name: "Blockade (Powerful)",
    slot: "Shield",
    tier: "Powerful",
    effect: "+4 Shielding",
    icon: WIKI_IMBU("Imbuement_Skillboost_Shielding3"),
    items: [
      { name: "Piece of Scarab Shell", quantity: 25 },
      { name: "Brimstone Shell", quantity: 25 },
      { name: "Frazzle Skin", quantity: 25 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== DEATH PROTECTION ======
  {
    id: "basic-lich-shroud",
    name: "Lich Shroud (Basic)",
    slot: "Armor",
    tier: "Basic",
    effect: "Reduz dano de Death em 2%",
    icon: WIKI_IMBU("Imbuement_Protection_Death1"),
    items: [{ name: "Flask of Embalming Fluid", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-lich-shroud",
    name: "Lich Shroud (Intricate)",
    slot: "Armor",
    tier: "Intricate",
    effect: "Reduz dano de Death em 5%",
    icon: WIKI_IMBU("Imbuement_Protection_Death2"),
    items: [
      { name: "Flask of Embalming Fluid", quantity: 25 },
      { name: "Gloom Wolf Fur", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-lich-shroud",
    name: "Lich Shroud (Powerful)",
    slot: "Armor",
    tier: "Powerful",
    effect: "Reduz dano de Death em 10%",
    icon: WIKI_IMBU("Imbuement_Protection_Death3"),
    items: [
      { name: "Flask of Embalming Fluid", quantity: 25 },
      { name: "Gloom Wolf Fur", quantity: 20 },
      { name: "Mystical Hourglass", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== FIRE PROTECTION ======
  {
    id: "basic-dragon-hide",
    name: "Dragon Hide (Basic)",
    slot: "Armor",
    tier: "Basic",
    effect: "Reduz dano de Fire em 3%",
    icon: WIKI_IMBU("Imbuement_Protection_Fire1"),
    items: [{ name: "Green Dragon Scale", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-dragon-hide",
    name: "Dragon Hide (Intricate)",
    slot: "Armor",
    tier: "Intricate",
    effect: "Reduz dano de Fire em 8%",
    icon: WIKI_IMBU("Imbuement_Protection_Fire2"),
    items: [
      { name: "Green Dragon Scale", quantity: 25 },
      { name: "Draken Sulphur", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-dragon-hide",
    name: "Dragon Hide (Powerful)",
    slot: "Armor",
    tier: "Powerful",
    effect: "Reduz dano de Fire em 15%",
    icon: WIKI_IMBU("Imbuement_Protection_Fire3"),
    items: [
      { name: "Green Dragon Scale", quantity: 25 },
      { name: "Draken Sulphur", quantity: 20 },
      { name: "White Pale", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== ENERGY PROTECTION ======
  {
    id: "basic-cloud-fabric",
    name: "Cloud Fabric (Basic)",
    slot: "Armor",
    tier: "Basic",
    effect: "Reduz dano de Energy em 3%",
    icon: WIKI_IMBU("Imbuement_Protection_Energy1"),
    items: [{ name: "Wyvern Talisman", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-cloud-fabric",
    name: "Cloud Fabric (Intricate)",
    slot: "Armor",
    tier: "Intricate",
    effect: "Reduz dano de Energy em 8%",
    icon: WIKI_IMBU("Imbuement_Protection_Energy2"),
    items: [
      { name: "Wyvern Talisman", quantity: 25 },
      { name: "Crawler Head Plating", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-cloud-fabric",
    name: "Cloud Fabric (Powerful)",
    slot: "Armor",
    tier: "Powerful",
    effect: "Reduz dano de Energy em 15%",
    icon: WIKI_IMBU("Imbuement_Protection_Energy3"),
    items: [
      { name: "Wyvern Talisman", quantity: 25 },
      { name: "Crawler Head Plating", quantity: 20 },
      { name: "White Pale", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== ICE PROTECTION ======
  {
    id: "basic-quara-scale",
    name: "Quara Scale (Basic)",
    slot: "Armor",
    tier: "Basic",
    effect: "Reduz dano de Ice em 3%",
    icon: WIKI_IMBU("Imbuement_Protection_Ice1"),
    items: [{ name: "Winter Wolf Fur", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-quara-scale",
    name: "Quara Scale (Intricate)",
    slot: "Armor",
    tier: "Intricate",
    effect: "Reduz dano de Ice em 8%",
    icon: WIKI_IMBU("Imbuement_Protection_Ice2"),
    items: [
      { name: "Winter Wolf Fur", quantity: 25 },
      { name: "Thick Fur", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-quara-scale",
    name: "Quara Scale (Powerful)",
    slot: "Armor",
    tier: "Powerful",
    effect: "Reduz dano de Ice em 15%",
    icon: WIKI_IMBU("Imbuement_Protection_Ice3"),
    items: [
      { name: "Winter Wolf Fur", quantity: 25 },
      { name: "Thick Fur", quantity: 20 },
      { name: "Deeptags", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== EARTH PROTECTION ======
  {
    id: "basic-snake-skin",
    name: "Snake Skin (Basic)",
    slot: "Armor",
    tier: "Basic",
    effect: "Reduz dano de Earth em 3%",
    icon: WIKI_IMBU("Imbuement_Protection_Earth1"),
    items: [{ name: "Piece of Swampling Wood", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-snake-skin",
    name: "Snake Skin (Intricate)",
    slot: "Armor",
    tier: "Intricate",
    effect: "Reduz dano de Earth em 8%",
    icon: WIKI_IMBU("Imbuement_Protection_Earth2"),
    items: [
      { name: "Piece of Swampling Wood", quantity: 25 },
      { name: "Snake Skin", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-snake-skin",
    name: "Snake Skin (Powerful)",
    slot: "Armor",
    tier: "Powerful",
    effect: "Reduz dano de Earth em 15%",
    icon: WIKI_IMBU("Imbuement_Protection_Earth3"),
    items: [
      { name: "Piece of Swampling Wood", quantity: 25 },
      { name: "Snake Skin", quantity: 20 },
      { name: "Deeptags", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },

  // ====== HOLY PROTECTION ======
  {
    id: "basic-demon-presence",
    name: "Demon Presence (Basic)",
    slot: "Armor",
    tier: "Basic",
    effect: "Reduz dano de Holy em 3%",
    icon: WIKI_IMBU("Imbuement_Protection_Holy1"),
    items: [{ name: "Cultish Mask", quantity: 20 }],
    cost: 7500,
    time: "20h",
  },
  {
    id: "intricate-demon-presence",
    name: "Demon Presence (Intricate)",
    slot: "Armor",
    tier: "Intricate",
    effect: "Reduz dano de Holy em 8%",
    icon: WIKI_IMBU("Imbuement_Protection_Holy2"),
    items: [
      { name: "Cultish Mask", quantity: 25 },
      { name: "Cultish Robe", quantity: 20 },
    ],
    cost: 60000,
    time: "20h",
  },
  {
    id: "powerful-demon-presence",
    name: "Demon Presence (Powerful)",
    slot: "Armor",
    tier: "Powerful",
    effect: "Reduz dano de Holy em 15%",
    icon: WIKI_IMBU("Imbuement_Protection_Holy3"),
    items: [
      { name: "Cultish Mask", quantity: 25 },
      { name: "Cultish Robe", quantity: 20 },
      { name: "Swan Feather Cloak", quantity: 5 },
    ],
    cost: 250000,
    time: "20h",
  },
];
