export const TIBIA_HUNTS = [
  "Abandoned Sewers",
  "Amazon Camp",
  "Ancient Ruins",
  "Ancient Scarabs",
  "Ankrahmun Tombs",
  "Asura Palace",
  "Asura Mirror",
  "Banuta",
  "Barkless Caves",
  "Beregar",
  "Blood Halls",
  "Buried Cathedral",
  "Carnivor's Rocks",
  "Carlin Cults",
  "Catacombs",
  "Chyllfroest",
  "Cobra Bastion",
  "Crystal Enigma",
  "Crystal Lakes",
  "Damaged Worker Golem",
  "Dark Faun Cave",
  "Darklight Core",
  "Dawnport",
  "Deeper Banuta",
  "Demon Forge",
  "Draken Walls",
  "Dragon Lair",
  "Drefia Grims",
  "Drume",
  "Edron Hero Cave",
  "Edron Orc Cave",
  "Elite Skeletons",
  "Energy Elemental Portal",
  "Exotic Cave",
  "Falcon Bastion",
  "Fenrock Dragon Lair",
  "Fenrock DL",
  "Ferumbras Ascendant",
  "Feyrist Nightmare Cave",
  "Feyrist Surface",
  "Flimsy Lost Souls",
  "Forgotten Library",
  "Formorgar Mines",
  "Frazzlemaws",
  "Fury Gate",
  "Gazer Spectres",
  "Glooth Bandits",
  "Glooth Factory",
  "Glooth Tower",
  "Gnomprona",
  "Goroma Demons",
  "Goroma Serpent Spawns",
  "Grimvale",
  "Grim Reapers Drefia",
  "Hive",
  "Hive East Tower",
  "Ice Library",
  "Ice Witch Temple",
  "Inner Sanctum",
  "Issavi Crypt",
  "Issavi Sewers",
  "Issavi Surface",
  "Juggernaut Cave",
  "Krailos Nightmare Ruins",
  "Krailos Spider Cave",
  "Lava Lurkers",
  "Liberty Bay Cults",
  "Library",
  "Lion Sanctum",
  "Lizard City",
  "Lizard Chosen",
  "Lower Roshamuul",
  "Medusa Tower",
  "Mino Cults",
  "Mirror Asura",
  "Moohtants",
  "Muggy Plains",
  "Museum of Tibian Arts",
  "Nightmare Isles",
  "Oramond Catacombs",
  "Oramond Dungeon",
  "Oramond Fury",
  "Oramond Glooth Bandits",
  "Oramond Minos",
  "Oramond Raid",
  "Oramond Sewers",
  "Oramond West",
  "Oramond Wild Life Raid",
  "Orcsoberfest",
  "Otherworld",
  "Pirats",
  "Plague Seal",
  "PoI Dragon Lords",
  "PoI Seals",
  "Prison",
  "Quara Grotto",
  "Razachai",
  "Razzagorn",
  "Rosh Prison",
  "Rosh Valley",
  "Roshamuul Bridge",
  "Roshamuul Depot",
  "Roshamuul Shockheads",
  "Roshamuul Silencers",
  "Rotten Golems",
  "Rotten Wasteland",
  "Salamandra Cave",
  "Sea Serpents",
  "Secret Library",
  "Shadow Tomb",
  "Skeleton Elite Cave",
  "Soul War",
  "Sphinx Cave",
  "Spike",
  "Summer Court",
  "Sunken Temple",
  "Svargrond Arena",
  "Talahu Medusa Cave",
  "True Asura",
  "Undead Dragons",
  "Vampire Crypt",
  "Vengoth Castle",
  "Wall Cluster",
  "Walls",
  "Warzone 1",
  "Warzone 2",
  "Warzone 3",
  "Warzone 4",
  "Warzone 5",
  "Warzone 6",
  "Warzone 7",
  "Warzone 8",
  "Warzone 9",
  "Werelions",
  "Werehyenas",
  "West Oramond",
  "Winter Court",
  "Wote",
  "Wrath of the Emperor",
  "Wyrms Drefia",
  "Yalahar Cults",
  "Yalahar Demons",
  "Yalahar Grims",
  "Yalahar Hellspawns",
  "Yielothax",
  "Zao Palace",
  "Zao Wailing Widow Cave",
  "Zugurosh",
].sort();
