export const TIBIA_HUNTS = [
  "Abandoned Sewers",
  "Ab'Dendriel Elf Cave",
  "Amazon Camp",
  "Ancient Scarabs",
  "Ankrahmun Dragon Lair",
  "Ankrahmun Tombs",
  "Asura Mirror",
  "Asura Mirror -1",
  "Asura Mirror -2",
  "Asura Palace",
  "Bakragore",
  "Banuta",
  "Banuta -1",
  "Banuta -2",
  "Banuta -3",
  "Banuta -4 (Last Floor)",
  "Banuta Surface",
  "Barkless Caves",
  "Beregar Mines",
  "Blood Halls",
  "Buried Cathedral",
  "Buried Cathedral -1",
  "Buried Cathedral -2",
  "Buried Cathedral -3",
  "Calassa Quaras",
  "Carlin Cults",
  "Carnivor's Rocks",
  "Catacombs (Goroma)",
  "Catacombs (Oramond)",
  "Catacombs (Yalahar)",
  "Chyllfroest",
  "Cobra Bastion",
  "Cobra Bastion -1",
  "Cobra Bastion -2",
  "Cormaya Dwarfs",
  "Crystal Enigma",
  "Crystal Lakes",
  "Cults (Carlin)",
  "Cults (Liberty Bay)",
  "Cults (Mino)",
  "Cults (Yalahar)",
  "Damaged Worker Golems",
  "Dark Faun Cave",
  "Darklight Core",
  "Darashia Dragon Lair",
  "Darashia Rotworms",
  "Dawnport",
  "Deepling Guard",
  "Deepling Spellsinger",
  "Deepling Warrior",
  "Deeper Banuta",
  "Demon Forge",
  "Demona",
  "Dragon Lair (Darashia)",
  "Dragon Lair (Fenrock)",
  "Dragon Lair (Goroma)",
  "Dragon Lord Cave (Fenrock)",
  "Dragon Lords (PoI)",
  "Draken Abominations",
  "Draken Walls",
  "Drakens (Razachai)",
  "Drefia Grim Reapers",
  "Drefia Wyrms",
  "Edron Demon Forge",
  "Edron Earth Elementals",
  "Edron Hero Cave",
  "Edron Orc Cave",
  "Edron Vampire Crypt",
  "Elfs (Yalahar)",
  "Energy Elemental Portal",
  "Exotic Cave",
  "Falcon Bastion",
  "Fenrock Dragon Lair",
  "Ferumbras Ascendant",
  "Ferumbras Ascendant -1",
  "Ferumbras Ascendant -2",
  "Feyrist Nightmare Cave",
  "Feyrist Surface",
  "Fibula Rotworms",
  "Fire Dragon Dojo",
  "Flimsy Lost Souls",
  "Forgotten Knowledge Bosses",
  "Formorgar Mines",
  "Frazzlemaw Bridge",
  "Frazzlemaws",
  "Fury Gate",
  "Gazer Spectres",
  "Gazer Spectres -1",
  "Glooth Bandits",
  "Glooth Factory",
  "Glooth Tower",
  "Gnomprona",
  "Goroma Demons",
  "Goroma Medusa",
  "Goroma Serpent Spawns",
  "Goroma SS/Medusa",
  "Gray Island (Hrodmir)",
  "Grim Reapers (Drefia)",
  "Grim Reapers (Yalahar)",
  "Grimvale",
  "Halls of Hope",
  "Hellfire Fighters",
  "Hellspawns (Yalahar)",
  "Hero Cave (Edron)",
  "Hive",
  "Hive East Tower",
  "Ice Library",
  "Ice Witch Temple",
  "Iksupan",
  "Ingol",
  "Ingol -1",
  "Ingol -2",
  "Ingol -3",
  "Inner Sanctum",
  "Issavi Crypt",
  "Issavi Crypt -1",
  "Issavi Crypt -2",
  "Issavi Lamassu",
  "Issavi Sewers",
  "Issavi Sphinx",
  "Issavi Surface",
  "Juggernaut Cave",
  "Kazordoon Mines",
  "Krailos Nightmare Ruins",
  "Krailos Spider Cave",
  "Krailos Surface",
  "Lava Lurkers",
  "Liberty Bay Cults",
  "Liberty Bay Quaras",
  "Liberty Bay Wyrms",
  "Lion Sanctum",
  "Lizard Chosen",
  "Lizard City",
  "Lizard Magistratus",
  "Lost Dwarves",
  "Lower Roshamuul",
  "Marapur",
  "Medusa Tower",
  "Meriana Gargoyles",
  "Mino Cults (Mintwallin)",
  "Minotaur Hills",
  "Mirror Asura",
  "Moohtants",
  "Muggy Plains",
  "Museum of Tibian Arts",
  "Muteraptor",
  "Nightmare Isles",
  "Okolnir",
  "Oramond Catacombs",
  "Oramond Dungeon",
  "Oramond Fury",
  "Oramond Glooth Bandits",
  "Oramond Hydra/Bog Raider",
  "Oramond Minos",
  "Oramond Raid",
  "Oramond Sewers",
  "Oramond West",
  "Oramond Wild Life Raid",
  "Orc Fortress",
  "Orcsoberfest",
  "Otherworld",
  "Pirats",
  "Plague Seal",
  "Plaguesmith",
  "PoI Dragon Lords",
  "PoI Seals",
  "Port Hope Water Elementals",
  "Prison (Roshamuul)",
  "Prison -1",
  "Prison -2",
  "Prison -3",
  "Putrid Mummies",
  "Quara Grotto (Liberty Bay)",
  "Quaras (Calassa)",
  "Quaras (Svargrond)",
  "Razachai",
  "Razzagorn",
  "Rosh Prison",
  "Roshamuul Prison",
  "Roshamuul Prison -1",
  "Roshamuul Prison -2",
  "Roshamuul Prison -3",
  "Rosh Valley",
  "Roshamuul Bridge",
  "Roshamuul Depot",
  "Roshamuul Shockheads",
  "Roshamuul Silencers",
  "Rotten Blood",
  "Rotten Blood (Bakragore)",
  "Rotten Blood (Arcanist)",
  "Rotten Golems",
  "Rotten Wasteland",
  "Salamandra Cave",
  "Sea Serpents",
  "Secret Library",
  "Secret Library (Ice)",
  "Secret Library (Energy)",
  "Secret Library (Fire)",
  "Shadow Tomb",
  "Skeleton Elite Cave",
  "Souleater Mountains",
  "Soul War",
  "Sphinx Cave (Issavi)",
  "Sphinx Cave -1",
  "Sphinx Cave -2",
  "Spike",
  "Stampors",
  "Summer Court",
  "Sunken Temple",
  "Svargrond Arena",
  "Svargrond Barbarians",
  "Svargrond Crystal Spiders",
  "Svargrond Formorgar Mines",
  "Svargrond Ice Golems",
  "Svargrond Okolnir",
  "Talahu Medusa Cave",
  "The Spike",
  "True Asura",
  "True Asura -1",
  "True Asura -2",
  "Undead Dragons",
  "Vampire Crypt (Edron)",
  "Vengoth Castle",
  "Venore Cults",
  "Venore Dragon Lair",
  "Wall Cluster",
  "Walls",
  "Warzone 1",
  "Warzone 2",
  "Warzone 3",
  "Warzone 4",
  "Warzone 5",
  "Warzone 6",
  "Warzone 7",
  "Warzone 8",
  "Warzone 9",
  "Weakend Frazzlemaw",
  "Werelions",
  "Werehyenas",
  "West Oramond",
  "Winter Court",
  "Wote (Wrath of the Emperor)",
  "Wyrms (Drefia)",
  "Wyrms (Liberty Bay)",
  "Yalahar Cults",
  "Yalahar Demons",
  "Yalahar Dragon Lair",
  "Yalahar Elfs",
  "Yalahar Grims",
  "Yalahar Hellspawns",
  "Yalahar Magicians",
  "Yalahar Minotaurs",
  "Yalahar Necromancers",
  "Yalahar Quaras",
  "Yalahar Workers",
  "Yielothax",
  "Zao Palace",
  "Zao Wailing Widow Cave",
  "Zugurosh",
].sort();
